# Generated by Django 5.0.2 on 2024-03-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
    ]
