# Generated by Django 5.0.2 on 2024-03-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_initial_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='initial_balance',
        ),
    ]
