# Generated by Django 5.0.2 on 2024-03-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
