# Generated by Django 5.0.2 on 2024-03-14 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traineepayment',
            name='trainee',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'trainee'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
