# Generated by Django 5.0.2 on 2024-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0003_traineepayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineepayment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
