# Generated by Django 5.0.2 on 2024-02-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_events_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='instructor',
        ),
    ]
