# Generated by Django 5.0.2 on 2024-02-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_remove_events_end_remove_events_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
