# Generated by Django 5.0.2 on 2024-03-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='user',
        ),
    ]
