# Generated by Django 5.0.2 on 2024-03-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
