# Generated by Django 5.0.2 on 2024-03-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_remove_events_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
