# Generated by Django 5.0.2 on 2024-03-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_remove_progress_course_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
