# Generated by Django 5.0.2 on 2024-02-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_events_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='instructor',
            new_name='instructorname',
        ),
    ]
